openapi: 3.0.3
info:
  title: Comex API
  description: O projeto é uma plataforma de e-commerce voltada para a venda de produtos de diferentes categorias. Ele permite o gerenciamento completo de produtos, clientes e categorias, oferecendo operações CRUD para cada entidade. O sistema também permite que clientes façam pedidos, visualizem produtos e gerenciem seus próprios dados.
  termsOfService: http://swagger.io/terms/
  contact:
    email: jacksondiego@gamil.com
  license:
    name: Apache
    url: http://www.apache.org/licenses
  version: v1
externalDocs:
  description: Documentação
  url: http://www.apache.org
servers:
  - url: https://localhost:7118

paths:

  /Categoria:
    get:
      tags:
        - Categoria
      summary: Recupera todos os produtos do banco de dados
      responses: 
        200: 
          description: Sucesso
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/categoria' 
        404:
          description: Produtos não encontrados
    post:
      tags:
        - Categoria
      summary: Adiciona um produto no banco de dados
      requestBody:
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/categoria' 
              
      responses:
        201:
          description: "Sucesso"
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/categoria' 
        400:
          description: "Falha ao criar categoria"
          
  /Categoria/{id}:
    get:
      tags:
        - Categoria
      summary: Recupera uma categoria do banco de dados através de um parâmetro {id}
      parameters:
      - name: id
        in: path
        description: ID do produto a ser buscado
        required: true
        schema:
          type: integer
            
      responses: 
        200: 
          description: Sucesso
          content: 
            application/json:
              schema: 
                 $ref: '#/components/schemas/categoria' 
        404:
          description: Produtos não encontrados
          
    put:
      tags:
        - Categoria
      summary: Atualiza uma categoria do banco de dados através de um parâmetro {id}
      parameters:
      - name: id
        in: path
        description: ID da categoria a ser atualizado
        required: true
        schema:
          type: integer
            
      requestBody:
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/categoria' 
              
      responses: 
        204: 
          description: Sem conteudo
        400:
          description: Falha ao atualizar o produto
    
    delete:
      tags:
        - Categoria
      summary: Remove uma categoria 
      parameters:
      - name: id
        in: path
        description: ID da categoria a ser excluído
        required: true
        schema:
          type: integer
          
      responses: 
        204: 
          description: Categoria excluído com sucesso
        400:
          description: Falha ao remover o produto
          
  /Endereco:
    get:
      tags:
        - Endereco
      summary: Recupera todos os enderecos do banco de dados
      responses: 
        200: 
          description: Sucesso
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/endereco' 
        404:
          description: Endereoo não encontrados
    post:
        tags:
          - Endereco
        summary: Adiciona um endereco no banco de dados
        requestBody:
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/endereco' 
                
        responses:
          201:
            description: "Sucesso"
            content: 
              application/json:
                schema: 
                  $ref: '#/components/schemas/endereco'
                  
  /Produtos:{id}:
    get:
      tags:
       - Endereco
      summary: Recupera um endereco do banco de dados através de um parâmetro {id}
      parameters:
      - name: id
        in: path
        description: ID do endereco a ser buscado
        required: true
        schema:
          type: integer
              
      responses: 
        200: 
          description: Sucesso
          content: 
            application/json:
              schema: 
                 $ref: '#/components/schemas/endereco' 
    put:
      tags:
        - Endereco
      summary: Atualiza um endereco do banco de dados através de um parâmetro {id}
      parameters:
      - name: id
        in: path
        description: ID do endereco a ser atualizado
        required: true
        schema:
          type: integer
            
      requestBody:
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/endereco' 
              
      responses: 
        204:
          description: Endereco atualizado com sucesso
        400:
          description: Falha ao atualizar o endereco
    
    delete:
      tags:
        - Endereco
      summary: Remove um endereco
      parameters: 
      - name: id
        in: path
        description: Id do endereco a ser excluído
        required: true
        schema:
          type: integer
      
      responses: 
        204: 
          description: Endereco excluído com sucesso
        400:
          description: Falha ao remover o endereco
          
  /Cliente:
    get:
      tags:
        - Endereco
      summary: Recupera todos os cliente do banco de dados
      responses: 
        200: 
          description: Sucesso
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/cliente'
    post:
        tags:
          - Cliente
        summary: Adiciona um cliente no banco de dados
        requestBody:
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/cliente' 
                
        responses:
          201:
            description: "Sucesso"
            content: 
              application/json:
                schema: 
                  $ref: '#/components/schemas/cliente'
                  
  /Cliente:{id}:
    get:
      tags:
       - Endereco
      summary: Recupera um cliente do banco de dados através de um parâmetro {id}
      parameters:
      - name: id
        in: path
        description: ID do cliente a ser buscado
        required: true
        schema:
          type: integer
              
      responses: 
        200: 
          description: Sucesso
          content: 
            application/json:
              schema: 
                 $ref: '#/components/schemas/cliente' 
        404:
          description: Cliente não encontrados
    put:
      tags:
        - Cliente
      summary: Atualiza um cliente no banco de dados através de um parâmetro {id}
      parameters:
      - name: id
        in: path
        description: Id do cliente a ser atualizado
        required: true
        schema:
          type: integer
            
      requestBody:
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/cliente' 
              
      responses: 
        204:
          description: Cliente atualizado com sucesso
        400:
          description: Falha ao atualizar o clente
    
    delete:
      tags:
        - Cliente
      summary: Remove um cliente
      parameters: 
      - name: id
        in: path
        description: Id do cliente a ser excluído
        required: true
        schema:
          type: integer
      
      responses: 
        204: 
          description: Cliente excluído com sucesso
        400:
          description: Falha ao remover o cliente
          
  
        
components:
  schemas:
    categoria:
      type: object
      properties:
        Id:
          type: integer
        nome:
          type: string
    endereco:
      type: object
      properties:
        Id:
          type: string
        Bairro:
          type: string
        Cidade:
          type: string
        Complemento:
          type: string
        Estado:
          type: string
        Rua:
          type: string
        Numero:
          type: integer
    cliente:
      type: object
      properties:
        Id:
          type: integer
        Nome:
          type: string
        CPF:
          type: string
        Email:
          type: string
        Profissao:
          type: string
        Telefone:
          type: string
        EnderecoId:
          type: integer
  